### PR TITLE
add ownerName and ownerKind to node props

### PR DESCRIPTION
**Pull request by richiepiya**
Signed-off-by: Richie Piya <rpiyasirisilp@gmail.com>

**Related Issue:**  https://github.com/open-cluster-management/backlog/issues/9000

**Description of changes**
- get owner name and kind for pod resources

### CODE REVIEW

**Comment by SherinV** [comment]
Is this scenario not handled by the `ownedBy` edges?

**Comment by richiepiya** [comment]
we need both the pod ownerName and ownerKind to match with resources that deploy these pods in app-ui

**Comment by SherinV** [comment]
> we need both the pod ownerName and ownerKind to match with resources that deploy these pods in app-ui

Capturing our discussion here - currently, we have this info in search. Searching for the pod will bring up the replication-controller as a related resource and vice-versa. @richiepiya to check if this info can be used for the topology use-case.

**Comment by richiepiya** [comment]
@SherinV updated the PR to conditionally pass the node properties

fyi @fxiang1

**Review by SherinV — APPROVED** [review]

**Pull request merged**
